
services:
  app:
    build:
      context: ./client
    volumes:
      - ./client/:/var/www/app
      - /var/www/app/node_modules
    working_dir: /var/www/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - api
  mysql:
    image: mysql:latest
    volumes:
      - mysql_data:/data/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: magicport_root
      MYSQL_USER: magicport
      MYSQL_DATABASE: magicport
      MYSQL_PASSWORD: secret
    networks:
      - api

  nginx:
    image: nginx:stable-alpine
    ports:
      - 8080:80
    volumes:
      - ./api/:/var/www/api
      - ./api/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx/:/var/log/nginx
    depends_on:
      - mysql
      - php
    networks:
      - api

  php:
    build:
      context: ./api
    volumes:
      - ./api/:/var/www/api
    working_dir: /var/www/api
    networks:
      - api

networks:
  api:

volumes:
  mysql_data:
    driver: local
